exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor

remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

author: Ris Plongée

timezone: Europe/Paris
encoding: utf-8
lang: fr-FR
title: Association Sportive Ris Plongée
logo: "/assets/logos/logo.svg"
email: risplongee+website@gmail.com
url: https://beta.ris-plongee.com
description: club associatif, loi 1901, affilié à la FFESSM et FSGT

navigation_header:
  - title: Accueil
    url: /
  - title: Nous contacter
    url: /contact.html
  - title: Notre agenda
    url: /agenda.html
  - title: Notre histoire
    url: /history.html