exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor

remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

author: Ris Plongée

timezone: Europe/Paris
encoding: utf-8
lang: fr-FR
title: Association Sportive Ris Plongée
email: adhesion@ris-plongee.com
url: https://beta.ris-plongee.com
description: Ris-Plongée, un club de plongée associatif à Ris-Orangis (91 )qui à plus de 50 ans..

navigation_header:
  - title: Association Sportive Ris Plongée
    url: /
  - title: Nous contacter
    url: /contact.html
  - title: Notre agenda
    url: /agenda.html
  - title: Réaliser un baptême de plongée
    url: /baptism.html
  - title: Adhérer au club
    url: https://www.helloasso.com/associations/asrp-ris-plongee/adhesions/adhesion-2023-2024
