exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor

remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

author: Ris Plongée

timezone: Europe/Paris
encoding: utf-8
lang: fr-FR
title: Association Sportive Ris Plongée
tagline: Plongée sous-marine Essonne
logo: "/assets/logos/logo.png"
email: risplongee+website@gmail.com
url: https://www.ris-plongee.com
description: "Découvrez la passion de la plongée avec Ris-plongée à Ris-Orangis, dans le département de l'Essonne. Des baptêmes gratuits chaque mercredi soir et des sorties en mer vous attendent. Rejoignez-nous dès aujourd'hui pour une aventure inoubliable !"

social_links: 
  Facebook: https://www.facebook.com/people/Ris-Plongée/pfbid081pvEYLc6cwrZXcnRv3nUq4jxbg2M18ahQA9adH7wRayQ1TBccToxqnR74VJpqENl/
  Instagram: https://www.instagram.com/risplongee/https://www.instagram.com/risplongee/

sharing_links:
  Email: true

seo_description_max_words: 200

navigation_header:
  - title: Actualités
    url: /blog.html
  - title: Le club
    url: /club.html
  - title: Nous contacter
    url: /contact.html
  - title: Notre agenda
    url: /agenda.html
  - title: Nos videos
    url: https://www.youtube.com/@RisPlongee

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap

collections:
  posts:
    feature_image: "/assets/img/cover.jpg"
